revno: 1411 [merge] author: Natalia <natalia.bidart@ubuntu.com> committer: Magicicada Bot branch nick: magicicada-client timestamp: Sat 2015-09-19 21:26:43 -0300 message:   [r=nataliabidart] - Avoid "ImportError: cannot import name get_program_path" on precise.   - Added missing dependency on python-qt4-dbus.